name: ImageMapAPI
version: 2.0.0
author: Dams333
main: ch.dams333.imagemap.Plugin
commands:
  map:
    description: Commande des maps
    permission: maps.map
  setmessage:
    description: Sauvegarder un message pour un poster
    permission: maps.msg